export const ADD_ADDRESS = 'ADD_ADDRESS';
export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_IDENTITIES = 'SET_IDENTITIES';
export const SET_RPC_TARGET = 'SET_RPC_TARGET';
